name: First Worfkflow
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: Multiple Command
        run: |
          node -v
          npm -v
